import Link from "next/link"; import type { CmsModule } from "../../../lib/cms"; import { deleteContent,saveContent,saveMovieRelationships } from "../actions";
type Option={id:string;name_en:string;name_te?:string|null};
type Credit={id:string;person_id:string;credit_type:string;character_name_en?:string|null;character_name_te?:string|null;billing_order?:number|null};
type CompanyLink={company_id:string;relationship_type:string};
export function EditorForm({module,record,people=[],companies=[],credits=[],companyLinks=[]}:{module:CmsModule;record?:Record<string,any>;people?:Option[];companies?:Option[];credits?:Credit[];companyLinks?:CompanyLink[]}){
 const movie=module.slug==="movies"&&record;
 return <><header className="cmsHead"><div><p>{module.titleTe}</p><h1>{record?"Edit":"New"} {module.title}</h1><span>Telugu + English · editorial timestamps are maintained on save</span></div><Link href={"/cms/"+module.slug}>Cancel</Link></header>
 <form action={saveContent} className="cmsForm"><input type="hidden" name="_module" value={module.slug}/><input type="hidden" name="_id" value={record?.id||""}/><div className="cmsFields">{module.fields.map(f=><label key={f.name} className={f.type==="textarea"?"wide":""}><span>{f.label}</span>{f.type==="textarea"?<textarea name={f.name} defaultValue={record?.[f.name]??""} rows={6}/>:f.type==="select"?<select name={f.name} defaultValue={record?.[f.name]??f.options?.[0]}>{f.options?.map(o=><option key={o}>{o}</option>)}</select>:f.type==="checkbox"?<input name={f.name} type="checkbox" defaultChecked={Boolean(record?.[f.name])}/>:<input name={f.name} type={f.type} step={f.step} required={f.required} defaultValue={record?.[f.name]??""}/>}</label>)}</div><div className="cmsFormBar"><button className="cmsButton" type="submit">Save content</button><span>RLS enforces editor/admin permissions.</span></div></form>
 {movie&&<section className="cmsRelation"><h2>Cast, Crew & Production Companies</h2><p>Link this movie to existing People / Celebrities and Companies. Add new people or companies in their CMS modules first.</p>
 <form action={saveMovieRelationships} className="cmsRelationForm"><input type="hidden" name="_movie_id" value={record.id}/>
 <h3>Cast & Crew</h3><div className="cmsRelationRows">{[...credits,{id:"",person_id:"",credit_type:"actor",character_name_en:"",character_name_te:"",billing_order:null}].map((c,i)=><div className="cmsRelationRow" key={c.id||"new-credit"}><select name={"credit_person_"+i} defaultValue={c.person_id}><option value="">Select person…</option>{people.map(p=><option key={p.id} value={p.id}>{p.name_en}{p.name_te?" · "+p.name_te:""}</option>)}</select><select name={"credit_type_"+i} defaultValue={c.credit_type}><option value="actor">Actor</option><option value="director">Director</option><option value="producer">Producer</option><option value="writer">Writer</option><option value="music_director">Music Director</option><option value="cinematographer">Cinematographer</option><option value="editor">Editor</option><option value="singer">Singer</option><option value="other">Other</option></select><input name={"character_en_"+i} defaultValue={c.character_name_en??""} placeholder="Character / role (English)"/><input name={"character_te_"+i} defaultValue={c.character_name_te??""} placeholder="పాత్ర / Role (Telugu)"/><input name={"billing_"+i} type="number" min="0" defaultValue={c.billing_order??""} placeholder="Order"/></div>)}</div><input type="hidden" name="_credit_rows" value={credits.length+1}/>
 <h3>Production Companies</h3><div className="cmsRelationRows">{[...companyLinks,{company_id:"",relationship_type:"production"}].map((c,i)=><div className="cmsCompanyRow" key={c.company_id||"new-company"}><select name={"company_"+i} defaultValue={c.company_id}><option value="">Select company…</option>{companies.map(p=><option key={p.id} value={p.id}>{p.name_en}{p.name_te?" · "+p.name_te:""}</option>)}</select><input name={"relationship_"+i} defaultValue={c.relationship_type} placeholder="production / distribution"/></div>)}</div><input type="hidden" name="_company_rows" value={companyLinks.length+1}/>
 <div className="cmsFormBar"><button className="cmsButton" type="submit">Save relationships</button><span>Existing links are replaced with the rows shown above.</span></div></form></section>}
 {record&&<form action={deleteContent} className="cmsDanger"><input type="hidden" name="_module" value={module.slug}/><input type="hidden" name="_id" value={record.id}/><button type="submit">Delete (admin only)</button></form>}</>;
}