import { notFound } from "next/navigation"; import { createSupabaseServerClient } from "../../../../lib/supabase/server"; import { getCmsModule } from "../../../../lib/cms"; import { EditorForm } from "../editor-form";
export default async function EditPage({params}:{params:Promise<{module:string,id:string}>}){const {module:slug,id}=await params;const module=getCmsModule(slug);if(!module)notFound();const supabase=await createSupabaseServerClient();const {data}=await supabase.from(module.table).select("*").eq("id",id).single();if(!data)notFound();
 let people:any[]=[];let companies:any[]=[];let credits:any[]=[];let companyLinks:any[]=[];let galleryImages:any[]=[];let ottMeta:Record<string,any>={};let reviewMovies:any[]=[];let reviewOttTitles:any[]=[];let boxOfficeMovies:any[]=[];let pollOptions:any[]=[];let contestEntries:any[]=[];
 if(slug==="galleries"){const g=await supabase.from("gallery_images").select("id,image_url,alt_en,alt_te,caption_en,caption_te,sort_order,credit").eq("gallery_id",id).order("sort_order",{ascending:true});galleryImages=g.data||[]}
 if(slug==="ott"){const er=await supabase.from("entity_registry").select("id").eq("entity_type","news_article").eq("entity_id",id).maybeSingle();if(er.data){const rel=await supabase.from("entity_relations").select("to_entity_id,metadata").eq("from_entity_id",er.data.id).eq("relation_type","featured_video").maybeSingle();if(rel.data){const target=await supabase.from("entity_registry").select("entity_id").eq("id",rel.data.to_entity_id).maybeSingle();if(target.data){const v=await supabase.from("videos").select("video_url").eq("id",target.data.entity_id).maybeSingle();ottMeta={...(rel.data.metadata||{}),video_url:v.data?.video_url||""}}}}}
 if(slug==="reviews"){const [m,o]=await Promise.all([supabase.from("movies").select("id,title_en,title_te").order("title_en").limit(1000),supabase.from("ott_titles").select("id,title_en,title_te").order("title_en").limit(1000)]);reviewMovies=(m.data||[]).map((x:any)=>({id:x.id,name_en:x.title_en,name_te:x.title_te}));reviewOttTitles=(o.data||[]).map((x:any)=>({id:x.id,name_en:x.title_en,name_te:x.title_te}));}
 if(slug==="contests"){const entries=await supabase.from("contest_entries").select("id,participant_name,participant_email,status,created_at").eq("contest_id",id).order("created_at",{ascending:false}).limit(100);contestEntries=entries.data||[];}
 if(slug==="polls"){const [o,v]=await Promise.all([supabase.from("poll_options").select("id,label_en,label_te,sort_order").eq("poll_id",id).order("sort_order",{ascending:true}),supabase.from("poll_votes").select("option_id").eq("poll_id",id)]);const counts:Record<string,number>={};for(const vote of v.data||[])counts[vote.option_id]=(counts[vote.option_id]||0)+1;pollOptions=(o.data||[]).map((x:any)=>({...x,vote_count:counts[x.id]||0}));}
 if(slug==="box-office"){const m=await supabase.from("movies").select("id,title_en,title_te").order("title_en").limit(1000);boxOfficeMovies=(m.data||[]).map((x:any)=>({id:x.id,name_en:x.title_en,name_te:x.title_te}));}
 if(slug==="movies"){const [p,c,cr,cl]=await Promise.all([supabase.from("people").select("id,name_en,name_te").order("name_en"),supabase.from("companies").select("id,name_en,name_te").order("name_en"),supabase.from("movie_credits").select("id,person_id,credit_type,character_name_en,character_name_te,billing_order").eq("movie_id",id).order("billing_order",{ascending:true,nullsFirst:false}),supabase.from("movie_companies").select("company_id,relationship_type").eq("movie_id",id)]);people=p.data||[];companies=c.data||[];credits=cr.data||[];companyLinks=cl.data||[]}
 return <EditorForm module={module} record={data} people={people} companies={companies} credits={credits} companyLinks={companyLinks} galleryImages={galleryImages} ottMeta={ottMeta} reviewMovies={reviewMovies} reviewOttTitles={reviewOttTitles} boxOfficeMovies={boxOfficeMovies} pollOptions={pollOptions} contestEntries={contestEntries}/>}
