export type FieldType="text"|"textarea"|"date"|"datetime-local"|"number"|"checkbox"|"url"|"select";
export type CmsField={name:string;label:string;type:FieldType;required?:boolean;options?:string[];step?:string};
export type CmsModule={slug:string;table:string;title:string;titleTe:string;entityType?:string;labelField:string;fields:CmsField[]};

const status: CmsField={name:"status",label:"Workflow status",type:"select",required:true,options:["draft","in_review","scheduled","published","archived"]};
const slug: CmsField={name:"slug",label:"Slug",type:"text",required:true};
const bilingual=(en:string,te:string,base="title"):CmsField[]=>[
 {name:base+"_en",label:en,type:"text",required:true},{name:base+"_te",label:te,type:"text"}
];
export const cmsModules:CmsModule[]=[
 {slug:"movies",table:"movies",title:"Movies",titleTe:"సినిమాలు",entityType:"movie",labelField:"title_en",fields:[slug,...bilingual("Title (English)","శీర్షిక (తెలుగు)"),{name:"synopsis_en",label:"Synopsis (English)",type:"textarea"},{name:"synopsis_te",label:"సారాంశం (తెలుగు)",type:"textarea"},{name:"release_date",label:"Release date",type:"date"},{name:"runtime_minutes",label:"Runtime (minutes)",type:"number"},{name:"certificate",label:"Certificate",type:"text"},{name:"language_code",label:"Language code (e.g. te)",type:"text"},{name:"country_code",label:"Country code (e.g. IN)",type:"text"},{name:"poster_url",label:"Poster URL",type:"url"},{name:"backdrop_url",label:"Backdrop URL",type:"url"},{name:"seo_title_en",label:"SEO title (English)",type:"text"},{name:"seo_title_te",label:"SEO title (Telugu)",type:"text"},{name:"seo_description_en",label:"SEO description (English)",type:"textarea"},{name:"seo_description_te",label:"SEO description (Telugu)",type:"textarea"},status]},
 {slug:"people",table:"people",title:"People / Celebrities",titleTe:"ప్రముఖులు",entityType:"person",labelField:"name_en",fields:[slug,...bilingual("Name (English)","పేరు (తెలుగు)","name"),{name:"bio_en",label:"Bio (English)",type:"textarea"},{name:"bio_te",label:"జీవిత విశేషాలు (తెలుగు)",type:"textarea"},{name:"date_of_birth",label:"Date of birth",type:"date"},{name:"primary_profession",label:"Primary profession",type:"select",options:["actor","actress","director","producer","writer","music_director","cinematographer","editor","singer","technician","other"]},{name:"profile_image_url",label:"Profile image URL",type:"url"},status]},
 {slug:"companies",table:"companies",title:"Companies / Production Houses",titleTe:"నిర్మాణ సంస్థలు",entityType:"company",labelField:"name_en",fields:[slug,...bilingual("Name (English)","పేరు (తెలుగు)","name"),{name:"description_en",label:"Description (English)",type:"textarea"},{name:"description_te",label:"వివరణ (తెలుగు)",type:"textarea"},{name:"company_type",label:"Company type",type:"select",options:["production_house","studio","distribution","ott_platform","music_label","post_production","vfx","other"]},{name:"logo_url",label:"Logo URL",type:"url"},{name:"website_url",label:"Website URL",type:"url"},status]},
 {slug:"news",table:"news_articles",title:"News Articles",titleTe:"వార్తలు",entityType:"news_article",labelField:"headline_en",fields:[slug,...bilingual("Headline (English)","హెడ్‌లైన్ (తెలుగు)","headline"),{name:"dek_en",label:"Summary (English)",type:"textarea"},{name:"dek_te",label:"సారాంశం (తెలుగు)",type:"textarea"},{name:"body_en",label:"Article (English)",type:"textarea"},{name:"body_te",label:"వార్త (తెలుగు)",type:"textarea"},{name:"hero_image_url",label:"Hero image URL",type:"url"},{name:"category",label:"Category",type:"select",options:["movies","celebrities","ott","box_office","trailers","events","interviews","industry","other"]},{name:"source_name",label:"Source / attribution",type:"text"},{name:"source_url",label:"Source URL",type:"url"},{name:"is_breaking",label:"Breaking news",type:"checkbox"},status]},
 {slug:"galleries",table:"image_galleries",title:"Image Galleries",titleTe:"ఫోటో గ్యాలరీలు",entityType:"gallery",labelField:"title_en",fields:[slug,...bilingual("Title (English)","శీర్షిక (తెలుగు)"),{name:"description_en",label:"Description (English)",type:"textarea"},{name:"description_te",label:"వివరణ (తెలుగు)",type:"textarea"},{name:"cover_image_url",label:"Cover image URL",type:"url"},status]},
 {slug:"videos",table:"videos",title:"Videos",titleTe:"వీడియోలు",entityType:"video",labelField:"title_en",fields:[slug,...bilingual("Title (English)","శీర్షిక (తెలుగు)"),{name:"description_en",label:"Description (English)",type:"textarea"},{name:"description_te",label:"వివరణ (తెలుగు)",type:"textarea"},{name:"platform",label:"Platform",type:"select",options:["video","youtube","instagram","facebook","x","other"]},{name:"external_id",label:"External ID / YouTube video ID",type:"text"},{name:"video_url",label:"Video URL (YouTube / Instagram / Facebook / X / hosted video)",type:"url"},{name:"thumbnail_url",label:"Thumbnail URL",type:"url"},{name:"duration_seconds",label:"Duration (seconds)",type:"number"},status]},
 {slug:"short-films",table:"short_films",title:"Short Films",titleTe:"షార్ట్ ఫిల్మ్స్",entityType:"short_film",labelField:"title_en",fields:[slug,...bilingual("Title (English)","శీర్షిక (తెలుగు)"),{name:"synopsis_en",label:"Synopsis (English)",type:"textarea"},{name:"synopsis_te",label:"సారాంశం (తెలుగు)",type:"textarea"},{name:"release_date",label:"Release date",type:"date"},{name:"poster_url",label:"Poster URL / YouTube thumbnail",type:"url"},status]},
 {slug:"ott",table:"ott_titles",title:"OTT",titleTe:"ఓటీటీ",entityType:"ott_title",labelField:"title_en",fields:[slug,...bilingual("Title (English)","శీర్షిక (తెలుగు)"),{name:"synopsis_en",label:"Synopsis (English)",type:"textarea"},{name:"synopsis_te",label:"సారాంశం (తెలుగు)",type:"textarea"},{name:"content_type",label:"Content type",type:"text"},{name:"release_date",label:"Release date",type:"date"},{name:"seasons",label:"Seasons",type:"number"},status]},
 {slug:"reviews",table:"reviews",title:"Reviews",titleTe:"రివ్యూలు",entityType:"review",labelField:"title_en",fields:[slug,...bilingual("Review title (English)","రివ్యూ శీర్షిక (తెలుగు)"),{name:"movie_id",label:"Movie UUID",type:"text"},{name:"ott_title_id",label:"OTT title UUID",type:"text"},{name:"body_en",label:"Review (English)",type:"textarea"},{name:"body_te",label:"రివ్యూ (తెలుగు)",type:"textarea"},{name:"rating",label:"Rating / 10",type:"number",step:"0.1"},{name:"verdict_en",label:"Verdict (English)",type:"textarea"},{name:"verdict_te",label:"తీర్పు (తెలుగు)",type:"textarea"},status]},
 {slug:"box-office",table:"box_office",title:"Box Office",titleTe:"బాక్సాఫీస్",entityType:"box_office",labelField:"territory",fields:[{name:"movie_id",label:"Movie UUID",type:"text",required:true},{name:"territory",label:"Territory",type:"text",required:true},{name:"period_type",label:"Period",type:"select",options:["daily","weekend","weekly","lifetime"]},{name:"period_start",label:"Period start",type:"date",required:true},{name:"period_end",label:"Period end",type:"date"},{name:"gross_amount",label:"Gross",type:"number",step:"0.01"},{name:"net_amount",label:"Net",type:"number",step:"0.01"},{name:"distributor_share",label:"Distributor share",type:"number",step:"0.01"},{name:"currency_code",label:"Currency",type:"text"},{name:"source_name",label:"Source",type:"text"},{name:"source_url",label:"Source URL",type:"url"},{name:"is_estimate",label:"Estimate",type:"checkbox"}]},
 {slug:"polls",table:"polls",title:"Polls",titleTe:"పోల్స్",entityType:"poll",labelField:"question_en",fields:[slug,...bilingual("Question (English)","ప్రశ్న (తెలుగు)","question"),{name:"description_en",label:"Description (English)",type:"textarea"},{name:"description_te",label:"వివరణ (తెలుగు)",type:"textarea"},{name:"starts_at",label:"Starts",type:"datetime-local"},{name:"ends_at",label:"Ends",type:"datetime-local"},{name:"allow_multiple",label:"Allow multiple choices",type:"checkbox"},status]},
 {slug:"contests",table:"contests",title:"Contests",titleTe:"పోటీలు",entityType:"contest",labelField:"title_en",fields:[slug,...bilingual("Title (English)","శీర్షిక (తెలుగు)"),{name:"description_en",label:"Description (English)",type:"textarea"},{name:"description_te",label:"వివరణ (తెలుగు)",type:"textarea"},{name:"rules_en",label:"Rules (English)",type:"textarea"},{name:"rules_te",label:"నియమాలు (తెలుగు)",type:"textarea"},{name:"starts_at",label:"Starts",type:"datetime-local"},{name:"ends_at",label:"Ends",type:"datetime-local"},status]}
];
export const getCmsModule=(slug:string)=>cmsModules.find(m=>m.slug===slug);
export const workflow=["draft","in_review","scheduled","published","archived"] as const;
