-- Applied to sfykcmbgsuzlyksosjny as 20261001124219 v1_auth_rbac_rls.
create type public.app_role as enum ('user','editor','admin');
create table public.user_roles(user_id uuid primary key references auth.users(id) on delete cascade,role public.app_role not null default 'user',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.user_roles enable row level security;
revoke all on public.user_roles from anon,authenticated; grant select on public.user_roles to authenticated;
create policy "users_read_own_role" on public.user_roles for select to authenticated using ((select auth.uid())=user_id);
create schema if not exists private; revoke all on schema private from public,anon,authenticated; grant usage on schema private to authenticated;
create or replace function private.current_app_role() returns public.app_role language sql stable security invoker set search_path='' as $$ select coalesce((select ur.role from public.user_roles ur where ur.user_id=(select auth.uid())),'user'::public.app_role) $$;
revoke all on function private.current_app_role() from public,anon; grant execute on function private.current_app_role() to authenticated;
grant select on public.movies,public.people,public.companies,public.movie_credits,public.movie_companies,public.news_articles,public.image_galleries,public.gallery_images,public.videos,public.short_films,public.ott_platforms,public.ott_titles,public.ott_availability,public.reviews,public.box_office,public.polls,public.poll_options,public.contests,public.tags,public.entity_registry,public.entity_relations,public.entity_tags,public.movie_pulse to anon,authenticated;
grant select,insert,update,delete on public.movies,public.people,public.companies,public.movie_credits,public.movie_companies,public.news_articles,public.image_galleries,public.gallery_images,public.videos,public.short_films,public.ott_platforms,public.ott_titles,public.ott_availability,public.reviews,public.box_office,public.polls,public.poll_options,public.contests,public.tags,public.entity_registry,public.entity_relations,public.entity_tags,public.editorial_items,public.editorial_revisions,public.movie_pulse to authenticated;
revoke all on public.poll_votes,public.contest_entries,public.editorial_items,public.editorial_revisions from anon;
grant select,insert,update,delete on public.poll_votes,public.contest_entries to authenticated;
do $$ declare t text; begin foreach t in array array['movies','people','companies','news_articles','image_galleries','videos','short_films','ott_titles','reviews','polls','contests'] loop
execute format('create policy %I on public.%I for select to anon, authenticated using (status = ''published''::public.content_status or (select private.current_app_role()) in (''editor''::public.app_role,''admin''::public.app_role))',t||'_read',t);
execute format('create policy %I on public.%I for insert to authenticated with check ((select private.current_app_role()) in (''editor''::public.app_role,''admin''::public.app_role))',t||'_staff_insert',t);
execute format('create policy %I on public.%I for update to authenticated using ((select private.current_app_role()) in (''editor''::public.app_role,''admin''::public.app_role)) with check ((select private.current_app_role()) in (''editor''::public.app_role,''admin''::public.app_role))',t||'_staff_update',t);
execute format('create policy %I on public.%I for delete to authenticated using ((select private.current_app_role())=''admin''::public.app_role)',t||'_admin_delete',t); end loop; end $$;
create policy movie_credits_read on public.movie_credits for select to anon,authenticated using(exists(select 1 from public.movies m where m.id=movie_id and m.status='published') or (select private.current_app_role()) in ('editor','admin'));
create policy movie_companies_read on public.movie_companies for select to anon,authenticated using(exists(select 1 from public.movies m where m.id=movie_id and m.status='published') or (select private.current_app_role()) in ('editor','admin'));
create policy gallery_images_read on public.gallery_images for select to anon,authenticated using(exists(select 1 from public.image_galleries g where g.id=gallery_id and g.status='published') or (select private.current_app_role()) in ('editor','admin'));
create policy ott_availability_read on public.ott_availability for select to anon,authenticated using(exists(select 1 from public.ott_titles o where o.id=ott_title_id and o.status='published') or (select private.current_app_role()) in ('editor','admin'));
create policy poll_options_read on public.poll_options for select to anon,authenticated using(exists(select 1 from public.polls p where p.id=poll_id and p.status='published') or (select private.current_app_role()) in ('editor','admin'));
create policy ott_platforms_read on public.ott_platforms for select to anon,authenticated using(true);
create policy tags_read on public.tags for select to anon,authenticated using(true);
create policy entity_registry_read on public.entity_registry for select to anon,authenticated using(true);
create policy entity_relations_read on public.entity_relations for select to anon,authenticated using(true);
create policy entity_tags_read on public.entity_tags for select to anon,authenticated using(true);
create policy box_office_read on public.box_office for select to anon,authenticated using(exists(select 1 from public.movies m where m.id=movie_id and m.status='published') or (select private.current_app_role()) in ('editor','admin'));
create policy movie_pulse_read on public.movie_pulse for select to anon,authenticated using(exists(select 1 from public.movies m where m.id=movie_id and m.status='published') or (select private.current_app_role()) in ('editor','admin'));
do $$ declare t text; begin foreach t in array array['movie_credits','movie_companies','gallery_images','ott_platforms','ott_availability','poll_options','tags','entity_registry','entity_relations','entity_tags','box_office','movie_pulse'] loop
execute format('create policy %I on public.%I for insert to authenticated with check ((select private.current_app_role()) in (''editor''::public.app_role,''admin''::public.app_role))',t||'_staff_insert',t);
execute format('create policy %I on public.%I for update to authenticated using ((select private.current_app_role()) in (''editor''::public.app_role,''admin''::public.app_role)) with check ((select private.current_app_role()) in (''editor''::public.app_role,''admin''::public.app_role))',t||'_staff_update',t);
execute format('create policy %I on public.%I for delete to authenticated using ((select private.current_app_role())=''admin''::public.app_role)',t||'_admin_delete',t); end loop; end $$;
create policy editorial_items_staff_read on public.editorial_items for select to authenticated using((select private.current_app_role()) in ('editor','admin'));
create policy editorial_items_staff_insert on public.editorial_items for insert to authenticated with check((select private.current_app_role()) in ('editor','admin'));
create policy editorial_items_staff_update on public.editorial_items for update to authenticated using((select private.current_app_role()) in ('editor','admin')) with check((select private.current_app_role()) in ('editor','admin'));
create policy editorial_items_admin_delete on public.editorial_items for delete to authenticated using((select private.current_app_role())='admin');
create policy editorial_revisions_staff_read on public.editorial_revisions for select to authenticated using((select private.current_app_role()) in ('editor','admin'));
create policy editorial_revisions_staff_insert on public.editorial_revisions for insert to authenticated with check((select private.current_app_role()) in ('editor','admin'));
create policy editorial_revisions_staff_update on public.editorial_revisions for update to authenticated using((select private.current_app_role()) in ('editor','admin')) with check((select private.current_app_role()) in ('editor','admin'));
create policy editorial_revisions_admin_delete on public.editorial_revisions for delete to authenticated using((select private.current_app_role())='admin');
create policy poll_votes_staff_read on public.poll_votes for select to authenticated using((select private.current_app_role()) in ('editor','admin'));
create policy poll_votes_staff_insert on public.poll_votes for insert to authenticated with check((select private.current_app_role()) in ('editor','admin'));
create policy poll_votes_staff_update on public.poll_votes for update to authenticated using((select private.current_app_role()) in ('editor','admin')) with check((select private.current_app_role()) in ('editor','admin'));
create policy poll_votes_admin_delete on public.poll_votes for delete to authenticated using((select private.current_app_role())='admin');
create policy contest_entries_staff_read on public.contest_entries for select to authenticated using((select private.current_app_role()) in ('editor','admin'));
create policy contest_entries_staff_insert on public.contest_entries for insert to authenticated with check((select private.current_app_role()) in ('editor','admin'));
create policy contest_entries_staff_update on public.contest_entries for update to authenticated using((select private.current_app_role()) in ('editor','admin')) with check((select private.current_app_role()) in ('editor','admin'));
create policy contest_entries_admin_delete on public.contest_entries for delete to authenticated using((select private.current_app_role())='admin');